name: coder0211
description: This is a package with functions and widgets to make app development faster and more convenient, currently it is developed by one developer.
version: 0.0.79
homepage: https://github.com/coder0211/coder0211-lib.git
repository: https://github.com/coder0211/coder0211-lib.git
license: MIT

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  #loading indicator
  loading_indicator: ^3.1.0

  #auto size text
  auto_size_text: ^3.0.0

  #conntection
  connectivity: ^3.0.6

  #shared preferences
  shared_preferences: ^2.0.11

  #image picker
  image_picker: ^0.8.4+4

  #dio
  dio: ^4.0.6

  #flutter toast
  fluttertoast: ^8.0.9

  #qr
  qr_flutter: ^4.0.0

  #svg
  flutter_svg: ^1.0.0

  #state managerment
  flutter_mobx: ^2.0.6+4
  mobx: ^2.1.1
  provider: ^6.0.4

  #font text
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
